resources:
- name: concourse-1
  type: registry-image
  source:
    repository: concourse/concourse
    foo: bar1
- name: concourse-2
  type: registry-image
  source:
    repository: concourse/concourse
    foo: bar2
- name: concourse-3
  type: registry-image
  source:
    repository: concourse/concourse
    foo: bar3
- name: concourse-4
  type: registry-image
  source:
    repository: concourse/concourse
    foo: bar4
- name: concourse-5
  type: registry-image
  source:
    repository: concourse/concourse
    foo: bar5
- name: concourse-6
  type: registry-image
  source:
    repository: concourse/concourse
    foo: bar6

jobs:
- name: stress-test
  plan:
  - get: concourse-1
  - get: concourse-2
  - get: concourse-3
  - get: concourse-4
  - get: concourse-5
  - get: concourse-6
    trigger: true
  - task: stream-in-everything
    privileged: true
    image: ubuntu
    config:
      inputs:
        - name: ubuntu
        - name: redis
        - name: mongo
        - name: node
        - name: mysql
        - name: postgres
        - name: registry
        - name: nginx
      platform: linux
      run:
        path: sh
        args:
        - -c
        - |
          #!/bin/bash
          echo "got em"
