resources:
- name: concourse-dev
  type: registry-image
  source:
    repository: concourse/dev
- name: gcloud
  type: registry-image
  source:
    repository: google/cloud-sdk
- name: ubuntu
  type: registry-image
  source:
    repository: ubuntu
- name: kubernetes
  type: git
  source:
    uri: https://github.com/kubernetes/kubernetes
- name: licensefinder
  type: registry-image
  source:
    repository: licensefinder/license_finder
- name: golang
  type: registry-image
  source:
    repository: golang

jobs:
- name: stress-test
  plan:
  - get: concourse-dev
  - get: gcloud
  - get: ubuntu
  - get: kubernetes
  - get: licensefinder
  - get: golang
    trigger: true
  - task: stream-in-everything
    privileged: true
    image: ubuntu
    config:
      inputs:
      - name: concourse-dev
      - name: gcloud
      - name: ubuntu
      - name: kubernetes
      - name: licensefinder
      - name: golang
      platform: linux
      run:
        path: sh
        args:
        - -c
        - |
          #!/bin/bash
          echo "got em"
