---
resources:
- name: some-resource
  type: bosh-io-release
  source:
    repository: concourse/concourse
    unique: ((hash))

jobs:
- name: some-job
  plan:
  - get: some-resource
    trigger: ((trigger))
