---
resources:
- name: passed-resource
  type: git
  source:
    uri: https://github.com/concourse/concourse.git

jobs:
- name: job1
  plan:
  - get: passed-resource

- name: job2
  plan:
  - get: passed-resource
    passed: [job1]
    trigger: true
  - task: output-hello
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: busybox
      run:
        path: sh
        args:
        - -c
        - |
          #!/bin/bash
          echo 'hello-world'

- name: job3
  plan:
  - get: passed-resource
    passed: [job2]
